# Generated by Django 3.2.9 on 2021-11-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211116_0916'),
    ]

    def fill_parts(apps, schema_editor):
        Car = apps.get_model('api', 'Car')
        CarPart = apps.get_model('api', 'CarPart')
        cars = Car.objects.all()
        for car in cars:
            for i in ['part one', 'part two', 'broken part']:
                CarPart(car=car, name=i, qty=3).save()


    operations = [
        migrations.RunPython(fill_parts),
    ]
